In [1]:
import sys
sys.path.append('/workspaces/ppo2048')
import jax
import jax.numpy as jnp
from jumanji.environments.logic.game_2048.env import Game2048
from ppo2048.networks import Networks

In [2]:
SEED = 0
SIZE = 4
BATCH_SIZE = 2

In [3]:
key = jax.random.PRNGKey(SEED)
env = Game2048(SIZE)

In [4]:
key, subkey = jax.random.split(key)
subkey = jax.random.split(subkey, BATCH_SIZE)
state, timestep = jax.vmap(env.reset)(subkey)
# state, timestep = env.reset(subkey)

In [5]:
networks = Networks.make((16, 8), 32, False)
key, subkey = jax.random.split(key)
params = networks.init(subkey)
networks.apply(params, timestep.observation)

(Array([[1.1098546,       inf, 1.1028546, 1.0833172],
        [1.4003812, 1.3691201, 1.4001706, 1.3759027]], dtype=float32),
 Array([0.0057175 , 0.01414741], dtype=float32))

In [11]:
networks = Networks.make((16, 8), 32, True)
key, subkey = jax.random.split(key)
params = networks.init(subkey)
neglogprobs, value = networks.apply(params, timestep.observation)
neglogprobs, value

(Array([[1.1178035,       inf, 1.0719049, 1.106704 ],
        [1.4046719, 1.3995982, 1.3531698, 1.3885505]], dtype=float32),
 Array([-0.00289111, -0.00152159], dtype=float32))